platform :ios, '11.0'

abstract_target 'ARKitEnvironmentMapper' do
  use_frameworks!

  target 'ARKitEnvironmentMapper_Example' do
    pod 'ARKitEnvironmentMapper', :path => '../'
  end

  target 'ARKitEnvironmentMapper_Tests' do
    pod 'ARKitEnvironmentMapper', :path => '../'
  end

end
