platform :ios, '11.0'

target 'ARKitEnvironmentMapper_Example' do
  use_frameworks!
  pod 'ARKitEnvironmentMapper', :path => '../'
end

target 'ARKitEnvironmentMapper_Tests' do
  use_frameworks!
  pod 'ARKitEnvironmentMapper', :path => '../'
end
